[Variables]

; NOTE: Remember to refresh the skin after saving your changes

;---------------------------------
;---------- PLAYER NAME ----------
;---------------------------------

; Set the media player to use
DefaultPlayerName=CAD


; AIMP: AIMP
; iTunes: iTunes
; foobar2000, J. River Media Center, Media Jukebox, MusicBee: CAD
; Winamp: Winamp
; WMP: WMP

; More info: https://docs.rainmeter.net/manual/measures/nowplaying/#playerlist
