[Variables]

; NOTE: Remember to refresh the skin after saving your changes

;---------------------------------
;------------ GENERAL ------------
;---------------------------------

; Image size for the cover art (default: 160)
CoverSize=160

; A multiplier that adjusts the roundness of the cover art (default: 0.1)
; Set value to 1 to make it circle
CoverRadius=0.1

; Set the color to tint the cover image (R,G,B) (default: 255,255,255)
CoverColorTint=255,255,255

; Set the cover image transparency/alpha value (default: 255)
CoverAlpha=255

; Make the cover image greyscaled (default: 0)
; Set value to 1 to enable
CoverGreyscale=0

; Controls how the cover art should be displayed (default: 2)
; NOTE: Mostly useful for adjusting youtube cover art
; The following values can be used:
; - 0 : Image scaled to fit. Ignore aspect ratio. 
; - 1 : Image scaled to fit. Preserve aspect ratio.
; - 2 : Image scaled & cropped. Preserve aspect ratio.
CoverAspectRatio=2

; Rotates the cover image (default: 0 degrees)
CoverImageRotate=0

; Flips the cover image (default: None)
; Choose one of the available values: (Horizontal, Vertical, Both)
CoverImageFlip=None

;---------------------------------
;---------- BACKGROUND -----------
;---------------------------------

; Set the background size (default: 0)
; Can be used as outline for the cover art (increase BackgroundAlpha value)
; Will adjust position of cover art automatically
BackgroundPadding=0

; Set the background color (R,G,B) (default: 0,0,0)
BackgroundColor=0,0,0

; Set the background transparency/alpha value (default: 1)
BackgroundAlpha=1
