[Variables]

; NOTE: Remember to refresh the skin after saving your changes

;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;
; CURRENTLY A WORK IN PROGRESS TO ADD USER INTERFACE ON FUTURE UPDATES
; 
; Other than improper variable names, most settings should work just fine.
; Until improvements have been made, please proceed with caution.
;
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

;---------------------------------
;------------ GENERAL ------------
;---------------------------------

; Set overall skin color (R,G,B) (default: 255,255,255)
ColorRGB=255,255,255

; Set the skin's transparency/alpha value (default: 255)
ColorAlpha=255

;---------------------------------
;---------- PLAYER ICON ----------
;---------------------------------

; Set player icon color (default: #ColorRGB#)
PlayerIconColor=#ColorRGB#

; Set player icon transparency/alpha value (default: #ColorAlpha#)
PlayerIconAlpha=#ColorAlpha#

;---------------------------------
;------------ ARTIST -------------
;---------------------------------

; Set song artist color (default: #ColorRGB#)
SongArtistColor=#ColorRGB#

; Set song artist transparency/alpha value (default: #ColorAlpha#)
SongArtistAlpha=#ColorAlpha#

; ----- GRADIENT SETTINGS -----

SongArtistGradientDegrees=180

SongArtistGradient1=#SongArtistColor#,#SongArtistAlpha#
SongArtistGradient1Percentage=0.0

SongArtistGradient2=#SongArtistColor#,#SongArtistAlpha#
SongArtistGradient2Percentage=0.5

SongArtistGradient3=#SongArtistColor#,#SongArtistAlpha#
SongArtistGradient3Percentage=1.0

;---------------------------------
;----------- SEPARATOR -----------
;---------------------------------

; Set separator color (default: #ColorRGB#)
SeparatorColor=#ColorRGB#

; Set separator transparency/alpha value (default: #ColorAlpha#)
SeparatorAlpha=#ColorAlpha#

; ----- GRADIENT SETTINGS -----

SeparatorGradientDegrees=180

SeparatorGradient1=#SeparatorColor#,#SeparatorAlpha#
SeparatorGradient1Percentage=0.0

SeparatorGradient2=#SeparatorColor#,#SeparatorAlpha#
SeparatorGradient2Percentage=0.5

SeparatorGradient3=#SeparatorColor#,#SeparatorAlpha#
SeparatorGradient3Percentage=1.0

;---------------------------------
;----------- ALBUM/TAG -----------
;---------------------------------

; Set song album/tag color (default: #ColorRGB#)
SongAlbumColor=#ColorRGB#

; Set song album/tag transparency/alpha value (default: #ColorAlpha#)
SongAlbumAlpha=#ColorAlpha#

; ----- GRADIENT SETTINGS -----

SongAlbumGradientDegrees=180

SongAlbumGradient1=#SongAlbumColor#,#SongAlbumAlpha#
SongAlbumGradient1Percentage=0.0

SongAlbumGradient2=#SongAlbumColor#,#SongAlbumAlpha#
SongAlbumGradient2Percentage=0.5

SongAlbumGradient3=#SongAlbumColor#,#SongAlbumAlpha#
SongAlbumGradient3Percentage=1.0

;---------------------------------
;------------ TITLE --------------
;---------------------------------

; Set song title color (default: #ColorRGB#)
SongTitleColor=#ColorRGB#

; Set song title transparency/alpha value (default: #ColorAlpha#)
SongTitleAlpha=#ColorAlpha#

; ----- GRADIENT SETTINGS -----

SongTitleGradientDegrees=180

SongTitleGradient1=#SongTitleColor#,#SongTitleAlpha#
SongTitleGradient1Percentage=0.0

SongTitleGradient2=#SongTitleColor#,#SongTitleAlpha#
SongTitleGradient2Percentage=0.5

SongTitleGradient3=#SongTitleColor#,#SongTitleAlpha#
SongTitleGradient3Percentage=1.0

;---------------------------------
;------------- LINE --------------
;---------------------------------

; Set line color (default: #ColorRGB#)
LineColor=#ColorRGB#

; Set line transparency/alpha value (default: #ColorAlpha#)
LineAlpha=#ColorAlpha#

; ----- GRADIENT SETTINGS -----

LineGradientDegrees=180

LineGradient1=#LineColor#,#LineAlpha#
LineGradient1Percentage=0.0

LineGradient2=#LineColor#,#LineAlpha#
LineGradient2Percentage=0.5

LineGradient3=#LineColor#,#LineAlpha#
LineGradient3Percentage=1.0

;---------------------------------
;--------- PROGRESS BAR ----------
;---------------------------------

; Set progress bar color (default: #ColorRGB#)
BarColor=#ColorRGB#

; Set progress bar transparency/alpha value (default: #ColorAlpha#)
BarAlpha=#ColorAlpha#

; Set background bar color (default: #BarColor#)
BackgroundBarColor=#BarColor#

; Set background bar transparency/alpha value (default: 30)
BackgroundBarAlpha=30

; ---- GRADIENT SETTINGS 1 ----

BarGradientDegrees=180

BarGradient1=#BarColor#,#BarAlpha#
BarGradient1Percentage=0.0

BarGradient2=#BarColor#,#BarAlpha#
BarGradient2Percentage=0.5

BarGradient3=#BarColor#,#BarAlpha#
BarGradient3Percentage=1.0

; ---- GRADIENT SETTINGS 2 ----

BackgroundBarGradientDegrees=180

BackgroundBarGradient1=#BackgroundBarColor#,#BackgroundBarAlpha#
BackgroundBarGradient1Percentage=0.0

BackgroundBarGradient2=#BackgroundBarColor#,#BackgroundBarAlpha#
BackgroundBarGradient2Percentage=0.5

BackgroundBarGradient3=#BackgroundBarColor#,#BackgroundBarAlpha#
BackgroundBarGradient3Percentage=1.0

;---------------------------------
;----------- POSITION ------------
;---------------------------------

; Set song position color (default: #ColorRGB#)
SongPositionColor=#ColorRGB#

; Set song position transparency/alpha value (default: #ColorAlpha#)
SongPositionAlpha=#ColorAlpha#

; ----- GRADIENT SETTINGS -----

SongPositionGradientDegrees=180

SongPositionGradient1=#SongPositionColor#,#SongPositionAlpha#
SongPositionGradient1Percentage=0.0

SongPositionGradient2=#SongPositionColor#,#SongPositionAlpha#
SongPositionGradient2Percentage=0.5

SongPositionGradient3=#SongPositionColor#,#SongPositionAlpha#
SongPositionGradient3Percentage=1.0

;---------------------------------
;----------- DURATION ------------
;---------------------------------

; Set song duration color (default: #ColorRGB#)
SongDurationColor=#ColorRGB#

; Set song duration transparency/alpha value (default: #ColorAlpha#)
SongDurationAlpha=#ColorAlpha#

; ----- GRADIENT SETTINGS -----

SongDurationGradientDegrees=180

SongDurationGradient1=#SongDurationColor#,#SongDurationAlpha#
SongDurationGradient1Percentage=0.0

SongDurationGradient2=#SongDurationColor#,#SongDurationAlpha#
SongDurationGradient2Percentage=0.5

SongDurationGradient3=#SongDurationColor#,#SongDurationAlpha#
SongDurationGradient3Percentage=1.0

;---------------------------------
;----------- CONTROLS ------------
;---------------------------------

; Set music controls color (default: #ColorRGB#)
ControlsColor=#ColorRGB#

; Set music controls transparency/alpha value (default: #ColorAlpha#)
ControlsAlpha=#ColorAlpha#

; -----------------------------

; Set volume down color (default: #ControlsColor#)
VolumeDownColor=#ControlsColor#

; Set volume down transparency/alpha value (default: #ControlsAlpha#)
VolumeDownAlpha=#ControlsAlpha#

; Set previous song color (default: #ControlsColor#)
PreviousSongColor=#ControlsColor#

; Set previous song transparency/alpha value (default: #ControlsAlpha#)
PreviousSongAlpha=#ControlsAlpha#

; Set play/pause color (default: #ControlsColor#)
PlayPauseColor=#ControlsColor#

; Set play/pause transparency/alpha value (default: #ControlsAlpha#)
PlayPauseAlpha=#ControlsAlpha#

; Set next song color (default: #ControlsColor#)
NextSongColor=#ControlsColor#

; Set next song transparency/alpha value (default: #ControlsAlpha#)
NextSongAlpha=#ControlsAlpha#

; Set volume up color (default: #ControlsColor#)
VolumeUpColor=#ControlsColor#

; Set volume up transparency/alpha value (default: #ControlsAlpha#)
VolumeUpAlpha=#ControlsAlpha#
