[Variables]

; NOTE: Remember to refresh the skin after saving your changes

;---------------------------------
;------------ GENERAL ------------
;---------------------------------

; Set certain skin color (R,G,B) (default: 255,255,255)
ColorRGB=255,255,255

; Set overall skin color (R,G,B,A) (default: 255,255,255,255)
ColorRGBA=255,255,255,255

;---------------------------------
;--------- TRACK INFO 1 ----------
;---------------------------------

; Set track info 1 color (default: #ColorRGBA#)
Position1Color=#ColorRGBA#

; ----- GRADIENT SETTINGS -----

Position1GradientDegrees=180

Position1Gradient1=#Position1Color#
Position1Gradient1Percentage=0.0

Position1Gradient2=#Position1Color#
Position1Gradient2Percentage=0.5

Position1Gradient3=#Position1Color#
Position1Gradient3Percentage=1.0

;---------------------------------
;---------- PLAYER ICON ----------
;---------------------------------

; Set player icon color (default: #ColorRGBA#)
PlayerIconColor=#ColorRGBA#

;---------------------------------
;--------- TRACK INFO 2 ----------
;---------------------------------

; Set track info 2 color (default: #ColorRGBA#)
Position2Color=#ColorRGBA#

; ----- GRADIENT SETTINGS -----

Position2GradientDegrees=180

Position2Gradient1=#Position2Color#
Position2Gradient1Percentage=0.0

Position2Gradient2=#Position2Color#
Position2Gradient2Percentage=0.5

Position2Gradient3=#Position2Color#
Position2Gradient3Percentage=1.0

;---------------------------------
;--------- TRACK INFO 3 ----------
;---------------------------------

; Set track info 3 color (default: #ColorRGBA#)
Position3Color=#ColorRGBA#

; ----- GRADIENT SETTINGS -----

Position3GradientDegrees=180

Position3Gradient1=#Position3Color#
Position3Gradient1Percentage=0.0

Position3Gradient2=#Position3Color#
Position3Gradient2Percentage=0.5

Position3Gradient3=#Position3Color#
Position3Gradient3Percentage=1.0

;---------------------------------
;------------- LINE --------------
;---------------------------------

; Set line color (default: #ColorRGBA#)
LineColor=#ColorRGBA#

; ----- GRADIENT SETTINGS -----

LineGradientDegrees=180

LineGradient1=#LineColor#
LineGradient1Percentage=0.0

LineGradient2=#LineColor#
LineGradient2Percentage=0.5

LineGradient3=#LineColor#
LineGradient3Percentage=1.0

;---------------------------------
;--------- PROGRESS BAR ----------
;---------------------------------

; Set progress bar color (default: #ColorRGBA#)
BarColor=#ColorRGBA#

; ---- GRADIENT SETTINGS ----

BarGradientDegrees=180

BarGradient1=#BarColor#
BarGradient1Percentage=0.0

BarGradient2=#BarColor#
BarGradient2Percentage=0.5

BarGradient3=#BarColor#
BarGradient3Percentage=1.0

;---------------------------------
;-------- BACKGROUND BAR ---------
;---------------------------------

; Set background bar color (default: #ColorRGB#,30)
BackgroundBarColor=#ColorRGB#,30

; ---- GRADIENT SETTINGS ----

BackgroundBarGradientDegrees=180

BackgroundBarGradient1=#BackgroundBarColor#
BackgroundBarGradient1Percentage=0.0

BackgroundBarGradient2=#BackgroundBarColor#
BackgroundBarGradient2Percentage=0.5

BackgroundBarGradient3=#BackgroundBarColor#
BackgroundBarGradient3Percentage=1.0

;---------------------------------
;-------- TRACK POSITION ---------
;---------------------------------

; Set track position color (default: #ColorRGBA#)
TrackPositionColor=#ColorRGBA#

; ----- GRADIENT SETTINGS -----

TrackPositionGradientDegrees=180

TrackPositionGradient1=#TrackPositionColor#
TrackPositionGradient1Percentage=0.0

TrackPositionGradient2=#TrackPositionColor#
TrackPositionGradient2Percentage=0.5

TrackPositionGradient3=#TrackPositionColor#
TrackPositionGradient3Percentage=1.0

;---------------------------------
;-------- TRACK DURATION ---------
;---------------------------------

; Set track duration color (default: #ColorRGBA#)
TrackDurationColor=#ColorRGBA#

; ----- GRADIENT SETTINGS -----

TrackDurationGradientDegrees=180

TrackDurationGradient1=#TrackDurationColor#
TrackDurationGradient1Percentage=0.0

TrackDurationGradient2=#TrackDurationColor#
TrackDurationGradient2Percentage=0.5

TrackDurationGradient3=#TrackDurationColor#
TrackDurationGradient3Percentage=1.0

;---------------------------------
;----------- CONTROLS ------------
;---------------------------------

; Set music controls color (default: #ColorRGBA#)
ControlsColor=#ColorRGBA#

; -----------------------------

; Set volume down color (default: #ControlsColor#)
VolumeDownColor=#ControlsColor#

; Set previous song color (default: #ControlsColor#)
PreviousSongColor=#ControlsColor#

; Set play/pause color (default: #ControlsColor#)
PlayPauseColor=#ControlsColor#

; Set next song color (default: #ControlsColor#)
NextSongColor=#ControlsColor#

; Set volume up color (default: #ControlsColor#)
VolumeUpColor=#ControlsColor#
